server:
  port: 8090
spring:
  application:
    name: yyApi-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///yyapi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# dubbo-springboot-demo-provider
dubbo:
  application:
    name: yyApi-backend-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
    id: nacos-registry

knife4j:
  enable: true
  openapi:
    title: yyApi 接口文档
    description: "一个接口开放平台"
    concat: wy
#    group:
#      dev:
#        api-rule: package
#        api-rule-resources:
#          - com.wy.yyApiBackend.controller.UserController
#          - com.wy.yyApiBackend.controller.UserInterfaceController
#          - com.wy.yyApiBackend.controller.InterfaceInfoController
